### ISSUE TITLE
[hauschmx] Automation exercise

### ISSUE THREAD

**Issue by cheriimoya** [Simulation-Software-Engineering/automation-exercise#8]
https://github.com/cheriimoya/sse-github-actions-exercise

**Comment by ajaust** [comment]
Looks good to me. I like that you have all dependencies in the `requirements.txt`. You are missing the call to `coverage report` in the `coverage_report` job to print the coverage report to the terminal.

**Comment by cheriimoya** [comment]
ah, you are right, i misread this part.
added it now, tho
